language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip setuptools
  - pip install --upgrade pytest pytest-cov coveralls
  - pip install -e .
script:
  - python setup.py test -a -v -a --cov=pyecoregen
after_success:
  - coveralls
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: 3.8
